name: Release PDF

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release and upload PDF
        uses: softprops/action-gh-release@v2
        with:
          files: |
            IzmirWildfire2025_Rapor_TR.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

